/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Coffee_Shop_Management_System;
       
        import java.util.Calendar;
        import java.util.GregorianCalendar;
        import java.awt.Color;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
        import java.text.SimpleDateFormat;
        import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Saifur Shamim
 */
public class Coffee_Shop_Management_System extends javax.swing.JFrame {

     double[] drink=new double[5];
     double[] cake=new double[8];
     double[] cost=new double[3];
     double[] i=new double[12];
     double[] tk=new double[3];
     
    /**
     * Creates new form Coffee_Shop_Management_System
     */
    public Coffee_Shop_Management_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jBtnReset = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JTextField();
        jlblTax = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jlblSubTotal = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jChkCuppuccino = new javax.swing.JCheckBox();
        jChkIceCuppuccno = new javax.swing.JCheckBox();
        jChkEspresso = new javax.swing.JCheckBox();
        jChkLattle = new javax.swing.JCheckBox();
        jChkIcedLattle = new javax.swing.JCheckBox();
        jtxtLattle = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jtxtIcedLattle = new javax.swing.JTextField();
        jtxtCuppuccino = new javax.swing.JTextField();
        jtxtIceCuppuccino = new javax.swing.JTextField();
        jtxtEspresso = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jChkCoffeeCake = new javax.swing.JCheckBox();
        jChkRed = new javax.swing.JCheckBox();
        jChkBlack = new javax.swing.JCheckBox();
        jChkLagos = new javax.swing.JCheckBox();
        jChkKillburn = new javax.swing.JCheckBox();
        jChkQueens = new javax.swing.JCheckBox();
        jtxtBlack = new javax.swing.JTextField();
        jtxtKillburn = new javax.swing.JTextField();
        jtxtLagos = new javax.swing.JTextField();
        jtxtCoffee = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jtxtRed = new javax.swing.JTextField();
        jtxtQueens = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jtxtCostDrinks = new javax.swing.JLabel();
        jtxtCostCake = new javax.swing.JLabel();
        jtxtService = new javax.swing.JLabel();
        jlblCostCake = new javax.swing.JTextField();
        jlblService = new javax.swing.JTextField();
        jlblCostDrinks = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setBackground(new java.awt.Color(102, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setText("Cafe Management System");

        jLabel3.setFont(new java.awt.Font("Wingdings", 0, 11)); // NOI18N
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(454, 454, 454)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 586, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 1770, -1));

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jBtnReset.setBackground(new java.awt.Color(0, 204, 204));
        jBtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnExit.setBackground(new java.awt.Color(0, 204, 204));
        jBtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        jBtnReceipt.setBackground(new java.awt.Color(0, 204, 204));
        jBtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReceipt.setText("Receipt");
        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceiptActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(72, 72, 72)
                .addComponent(jBtnReceipt)
                .addGap(55, 55, 55)
                .addComponent(jBtnReset)
                .addGap(76, 76, 76)
                .addComponent(jBtnExit)
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnReset)
                    .addComponent(jBtnExit)
                    .addComponent(jBtnReceipt)
                    .addComponent(jButton1))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 700, 680, 210));

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTax.setText("VAT");

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSubTotal.setText("Sub Total");

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTotal.setText("Total");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblTotal.setText("0");
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblTax.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblTax.setText("0");
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblSubTotal.setText("0");
        jlblSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jtxtSubTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                        .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jtxtTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(272, Short.MAX_VALUE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(128, 128, 128)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(282, Short.MAX_VALUE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(118, 118, 118)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTax)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSubTotal)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTotal)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(197, Short.MAX_VALUE)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(187, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 520, 300));

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChkCuppuccino.setBackground(new java.awt.Color(204, 102, 255));
        jChkCuppuccino.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkCuppuccino.setText("Cuppuccino");
        jChkCuppuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCuppuccinoMouseClicked(evt);
            }
        });
        jChkCuppuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCuppuccinoActionPerformed(evt);
            }
        });

        jChkIceCuppuccno.setBackground(new java.awt.Color(204, 102, 255));
        jChkIceCuppuccno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkIceCuppuccno.setText("Ice Cuppuccino");
        jChkIceCuppuccno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIceCuppuccnoMouseClicked(evt);
            }
        });

        jChkEspresso.setBackground(new java.awt.Color(204, 102, 255));
        jChkEspresso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkEspresso.setText("Espresso");
        jChkEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkEspressoMouseClicked(evt);
            }
        });
        jChkEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkEspressoActionPerformed(evt);
            }
        });

        jChkLattle.setBackground(new java.awt.Color(204, 102, 255));
        jChkLattle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkLattle.setText("Lattle");
        jChkLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkLattleMouseClicked(evt);
            }
        });
        jChkLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLattleActionPerformed(evt);
            }
        });

        jChkIcedLattle.setBackground(new java.awt.Color(204, 102, 255));
        jChkIcedLattle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkIcedLattle.setText("Iced Lattle");
        jChkIcedLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIcedLattleMouseClicked(evt);
            }
        });

        jtxtLattle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLattle.setText("0");
        jtxtLattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLattleMouseClicked(evt);
            }
        });
        jtxtLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLattleActionPerformed(evt);
            }
        });

        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtIcedLattle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtIcedLattle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIcedLattle.setText("0");
        jtxtIcedLattle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtIcedLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIcedLattleMouseClicked(evt);
            }
        });
        jtxtIcedLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIcedLattleActionPerformed(evt);
            }
        });

        jtxtCuppuccino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtCuppuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCuppuccino.setText("0");
        jtxtCuppuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtCuppuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCuppuccinoMouseClicked(evt);
            }
        });
        jtxtCuppuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCuppuccinoActionPerformed(evt);
            }
        });

        jtxtIceCuppuccino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtIceCuppuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIceCuppuccino.setText("0");
        jtxtIceCuppuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtIceCuppuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIceCuppuccinoMouseClicked(evt);
            }
        });

        jtxtEspresso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtEspresso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtEspresso.setText("0");
        jtxtEspresso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtEspressoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jChkIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChkIceCuppuccno)
                            .addComponent(jChkEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChkCuppuccino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtCuppuccino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtIceCuppuccino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEspresso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jChkLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(362, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(68, 68, 68)))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addContainerGap(372, Short.MAX_VALUE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkCuppuccino)
                    .addComponent(jtxtCuppuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkIceCuppuccno)
                    .addComponent(jtxtIceCuppuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkLattle)
                    .addComponent(jtxtLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkIcedLattle)
                    .addComponent(jtxtIcedLattle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(412, Short.MAX_VALUE)))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(402, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 550, 490));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jChkCoffeeCake.setBackground(new java.awt.Color(102, 102, 255));
        jChkCoffeeCake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkCoffeeCake.setText("Coffee Cake");
        jChkCoffeeCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCoffeeCakeMouseClicked(evt);
            }
        });
        jChkCoffeeCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCoffeeCakeActionPerformed(evt);
            }
        });

        jChkRed.setBackground(new java.awt.Color(102, 102, 255));
        jChkRed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkRed.setText("Red Velvet Cake");
        jChkRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkRedMouseClicked(evt);
            }
        });
        jChkRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkRedActionPerformed(evt);
            }
        });

        jChkBlack.setBackground(new java.awt.Color(102, 102, 255));
        jChkBlack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkBlack.setText("Black Forest Cake");
        jChkBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkBlackMouseClicked(evt);
            }
        });
        jChkBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBlackActionPerformed(evt);
            }
        });

        jChkLagos.setBackground(new java.awt.Color(102, 102, 255));
        jChkLagos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkLagos.setText("Lagos Chocolate Cake");
        jChkLagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkLagosMouseClicked(evt);
            }
        });
        jChkLagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLagosActionPerformed(evt);
            }
        });

        jChkKillburn.setBackground(new java.awt.Color(102, 102, 255));
        jChkKillburn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkKillburn.setText("KIllburn Chocolate Cake");
        jChkKillburn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkKillburnMouseClicked(evt);
            }
        });
        jChkKillburn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkKillburnActionPerformed(evt);
            }
        });

        jChkQueens.setBackground(new java.awt.Color(102, 102, 255));
        jChkQueens.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkQueens.setText("Queen's Park Chocolate Cake");
        jChkQueens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkQueensMouseClicked(evt);
            }
        });
        jChkQueens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkQueensActionPerformed(evt);
            }
        });

        jtxtBlack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtBlack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBlack.setText("0");
        jtxtBlack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBlackMouseClicked(evt);
            }
        });

        jtxtKillburn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtKillburn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtKillburn.setText("0");
        jtxtKillburn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtKillburn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtKillburnMouseClicked(evt);
            }
        });

        jtxtLagos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtLagos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLagos.setText("0");
        jtxtLagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtLagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLagosMouseClicked(evt);
            }
        });

        jtxtCoffee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtCoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCoffee.setText("0");
        jtxtCoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCoffeeMouseClicked(evt);
            }
        });

        jTextField20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtRed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtRed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtRed.setText("0");
        jtxtRed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtRedMouseClicked(evt);
            }
        });

        jtxtQueens.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtQueens.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtQueens.setText("0");
        jtxtQueens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtQueens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtQueensMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkQueens)
                    .addComponent(jChkKillburn)
                    .addComponent(jChkLagos)
                    .addComponent(jChkBlack)
                    .addComponent(jChkCoffeeCake)
                    .addComponent(jChkRed, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtQueens, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtKillburn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtRed, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(380, Short.MAX_VALUE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(390, Short.MAX_VALUE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkCoffeeCake)
                    .addComponent(jtxtCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkRed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtRed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkBlack)
                    .addComponent(jtxtBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkLagos)
                    .addComponent(jtxtLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jChkKillburn)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jtxtKillburn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jChkQueens)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jtxtQueens, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(423, Short.MAX_VALUE)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(413, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 520, 490));

        jPanel6.setBackground(new java.awt.Color(51, 0, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 120, 680, 570));

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtCostDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCostDrinks.setText("Cost of Drinks");

        jtxtCostCake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCostCake.setText("Cost of Cakes");

        jtxtService.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtService.setText("Service Charge");

        jlblCostCake.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblCostCake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblCostCake.setText("0");
        jlblCostCake.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblService.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblService.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblService.setText("100");
        jlblService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblCostDrinks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlblCostDrinks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlblCostDrinks.setText("0");
        jlblCostDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCostCake)
                    .addComponent(jtxtService)
                    .addComponent(jtxtCostDrinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblService, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostCake, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jtxtCostDrinks))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jlblCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtCostCake)
                    .addComponent(jlblCostCake, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtService)
                    .addComponent(jlblService, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jChkLagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkLagosActionPerformed

    private void jChkLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkLattleActionPerformed

    private void jtxtLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLattleActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        
        jlblCostCake.setText("0");
        jlblCostDrinks.setText("0");
        jlblService.setText("100");
        jlblTax.setText("0");
        jlblSubTotal.setText("0");
        jlblTotal.setText("0");
        jtxtCoffee.setText("0");
        jtxtRed.setText("0");
        jtxtBlack.setText("0");
        jtxtLagos.setText("0");
        jtxtKillburn.setText("0");
        jtxtQueens.setText("0");
        jtxtLattle.setText("0");
        jtxtIcedLattle.setText("0");
        jtxtCuppuccino.setText("0");
        jtxtIceCuppuccino.setText("0");
        jtxtEspresso.setText("0");
        //====================================
        jtxtReceipt.setText(null);
        //====================================
        jChkLattle.setSelected(false);
        jChkIcedLattle.setSelected(false);
        jChkCuppuccino.setSelected(false);
        jChkIceCuppuccno.setSelected(false);
        jChkEspresso.setSelected(false);
        jChkCoffeeCake.setSelected(false);
        jChkRed.setSelected(false);
        jChkBlack.setSelected(false);
        jChkLagos.setSelected(false);
        jChkKillburn.setSelected(false);
        jChkQueens.setSelected(false);
        
        
        
        
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jChkEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkEspressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkEspressoActionPerformed

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed
        
        drink[0]=Double.parseDouble(jtxtLattle.getText());
        drink[1]=Double.parseDouble(jtxtIcedLattle.getText());
        drink[2]=Double.parseDouble(jtxtCuppuccino.getText());
        drink[3]=Double.parseDouble(jtxtIceCuppuccino.getText());
        drink[4]=Double.parseDouble(jtxtEspresso.getText());
        
        
        cake[0]=Double.parseDouble(jtxtCoffee.getText());
        cake[1]=Double.parseDouble(jtxtRed.getText());
        cake[2]=Double.parseDouble(jtxtBlack.getText());
        cake[3]=Double.parseDouble(jtxtLagos.getText());
        cake[4]=Double.parseDouble(jtxtKillburn.getText());
        cake[5]=Double.parseDouble(jtxtQueens.getText());
        
        cost[0]=Double.parseDouble(jlblTax.getText());
        cost[1]=Double.parseDouble(jlblSubTotal.getText());
        cost[2]=Double.parseDouble(jlblTotal.getText());
       
        
   
        
        //--------------------------------------------------------------
        
       
        int rfs=1325+(int) (Math.random()*4238);
        
        
        //-------------------------------------------------------------------
         Calendar timer=Calendar.getInstance();
         timer.getTime();
         SimpleDateFormat tTime= new SimpleDateFormat("HH:mm:ss");
         tTime.format(timer.getTime());
         SimpleDateFormat tDate= new SimpleDateFormat("dd-MMM-yyyy");
         tDate.format(timer.getTime());
        
        //-----------------------------------------------------------
        jtxtReceipt.append("\n\n\n\tCafe Management System: \n\n" +
                "\n\tReference:"+ rfs +
                "\n\t====================================\t"+
                "\n\tLattle:\t\t\t      "+ drink[0] + 
                "\n\tIced Lattle:\t\t      "+ drink[1] + 
                "\n\tCuppuccino:\t\t      "+ drink[2] +
                "\n\tIce Cuppuccino:\t\t      "+ drink[3] +
                "\n\tEspresso:\t\t      "+ drink[4] +
                  
                "\n\t=====================================\t\t "+
                "\n\tCoffee Cake:\t\t        " + cake[0] +
                "\n\tRed Velvet Cake:\t        " + cake[1] +  
                "\n\tBlack Forest Cake:\t        " + cake[2] +
                "\n\tLagos Chocolate Cake:\t        " + cake[3] +
                "\n\tKillburn Chocolate Cake:\t" + cake[4] +
                "\n\tQueen's Park Chocolate Cake:\t" + cake[5] +
                "\n\t=======================================\t\t "+
                        
                "\n\tVAT:\t\t\t\t" + cost[0] +   
                "\n\tSub Total:\t\t\t" + cost[1] + 
                "\n\tTotal:\t\t\t\t" + cost[2] + 
                "\n\t=======================================\t\t "+
                "\n\n\tDate: "+tDate.format(timer.getTime()) +
                "   Time: "+tTime.format(timer.getTime()) +
                "\n\n \t\t   Thank You");
        
        db d = new db();
        String q = "INSERT INTO receipt VALUES("+rfs+",'"+tDate.format(timer.getTime())+"','"+drink[0]+"','"+drink[1]+"','"+drink[2]+"','"+drink[3]+"','"+drink[4]+"','"+cake[0]+"','"+cake[1]+"','"+cake[2]+"','"+cake[3]+"','"+cake[4]+"','"+cake[5]+"','"+cost[0]+"','"+cost[1]+"','"+cost[2]+"')";
         try {
             d.s.executeUpdate(q);
         } catch (SQLException ex) {
             System.out.println(ex);
         }
    }//GEN-LAST:event_jBtnReceiptActionPerformed

    private void jtxtIcedLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIcedLattleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIcedLattleActionPerformed

     
    private void jChkCuppuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCuppuccinoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jChkCuppuccinoActionPerformed
      //jPanel5MouseClicked(evt)
    
    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt)
    {
        
    }
    private void jtxtCuppuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCuppuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCuppuccinoActionPerformed

    private void jChkIcedLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIcedLattleMouseClicked
        // TODO add your handling code here:
        double cIcedLattle=Double.parseDouble(jlblCostDrinks.getText());
        double IcedLattle=Double.parseDouble(jtxtIcedLattle.getText());
        double iIcedLattle=100.00;
        
        if(jChkIcedLattle.isSelected())
        {
            i[2]=(IcedLattle*iIcedLattle)+cIcedLattle;
            String pDrink=String.format("%.2f", i[2]);
            jlblCostDrinks.setText(pDrink);
            //jtxtIcedLattle.setText(pDrink);
        }
    }//GEN-LAST:event_jChkIcedLattleMouseClicked

    private void jChkCuppuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCuppuccinoMouseClicked
        // TODO add your handling code here:
        
         
        double cCap=Double.parseDouble(jlblCostDrinks.getText());
        double Cuppuccino=Double.parseDouble(jtxtCuppuccino.getText());
        double iCuppuccino=130.00;
        
        if(jChkCuppuccino.isSelected())
        {
            i[0]=(Cuppuccino*iCuppuccino)+cCap;
            
            String pDrink=String.format("%.2f", i[0]);
            jlblCostDrinks.setText(pDrink);
            //jtxtCuppuccino.setText(pDrink);
        }
    
    }//GEN-LAST:event_jChkCuppuccinoMouseClicked

    private void jChkLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkLattleMouseClicked
        // TODO add your handling code here:
        
        double cLattle=Double.parseDouble(jlblCostDrinks.getText());
        double Lattle=Double.parseDouble(jtxtLattle.getText());
        double iLattle=80.00;
        
        if(jChkLattle.isSelected())
        {
            i[1]=(Lattle*iLattle)+cLattle;
            String pDrink=String.format("%.2f", i[1]);
            jlblCostDrinks.setText(pDrink);
            //jtxtLattle.setText(pDrink);
        }
    }//GEN-LAST:event_jChkLattleMouseClicked

    private void jChkEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkEspressoMouseClicked
        // TODO add your handling code here:
        double cEspresso=Double.parseDouble(jlblCostDrinks.getText());
        double Espresso=Double.parseDouble(jtxtEspresso.getText());
        double iEspresso=95.00;
        
        if(jChkEspresso.isSelected())
        {
            i[3]=(Espresso*iEspresso)+cEspresso;
            String pDrink=String.format("%.2f", i[3]);
            jlblCostDrinks.setText(pDrink);
            //jtxtEspresso.setText(pDrink);
        }
    }//GEN-LAST:event_jChkEspressoMouseClicked

    private void jChkIceCuppuccnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIceCuppuccnoMouseClicked
        // TODO add your handling code here:
        double cIceCuppuccino=Double.parseDouble(jlblCostDrinks.getText());
        double IceCuppuccino=Double.parseDouble(jtxtIceCuppuccino.getText());
        double iIceCuppuccino=125.00;
        
        if(jChkIceCuppuccno.isSelected())
        {
            i[4]=(IceCuppuccino*iIceCuppuccino)+cIceCuppuccino;
            String pDrink=String.format("%.2f", i[4]);
            jlblCostDrinks.setText(pDrink);
            //jtxtEspresso.setText(pDrink);
        }
    }//GEN-LAST:event_jChkIceCuppuccnoMouseClicked

    private void jChkCoffeeCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCoffeeCakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkCoffeeCakeActionPerformed

    private void jChkCoffeeCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCoffeeCakeMouseClicked
        // TODO add your handling code here:
        
        double cCoffeeCake=Double.parseDouble(jlblCostCake.getText());
        double CoffeeCake=Double.parseDouble(jtxtCoffee.getText());
        double iCoffeeCake=55.00;
        
        if(jChkCoffeeCake.isSelected())
        {
            i[5]=(CoffeeCake*iCoffeeCake)+cCoffeeCake;
            String pCoffeeCake=String.format("%.2f", i[5]);
            jlblCostCake.setText(pCoffeeCake);
            
        }
    }//GEN-LAST:event_jChkCoffeeCakeMouseClicked

    private void jChkRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkRedActionPerformed
/*
    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked
*/
    private void jChkRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkRedMouseClicked
        // TODO add your handling code here:
        
        double cRedVelvet=Double.parseDouble(jlblCostCake.getText());
        double RedVelvet=Double.parseDouble(jtxtRed.getText());
        double iRedVelvet=60.00;
        
        if(jChkRed.isSelected())
        {
            i[6]=(RedVelvet*iRedVelvet)+cRedVelvet;
            String pCoffeeCake=String.format("%.2f", i[6]);
            jlblCostCake.setText(pCoffeeCake);
            
        }
    }//GEN-LAST:event_jChkRedMouseClicked

    private void jChkBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBlackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkBlackActionPerformed

    private void jChkBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkBlackMouseClicked
        // TODO add your handling code here:
        
        double cBlack=Double.parseDouble(jlblCostCake.getText());
        double Black=Double.parseDouble(jtxtBlack.getText());
        double iBlack=63.00;
        
        if(jChkBlack.isSelected())
        {
            i[7]=(Black*iBlack)+cBlack;
            String pCoffeeCake=String.format("%.2f", i[7]);
            jlblCostCake.setText(pCoffeeCake);
            
        }
    }//GEN-LAST:event_jChkBlackMouseClicked

    private void jChkLagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkLagosMouseClicked
        // TODO add your handling code here:
        
        double cLagos=Double.parseDouble(jlblCostCake.getText());
        double Lagos=Double.parseDouble(jtxtLagos.getText());
        double iLagos=65.00;
        
        if(jChkLagos.isSelected())
        {
            i[8]=(Lagos*iLagos)+cLagos;
            String pCoffeeCake=String.format("%.2f", i[8]);
            jlblCostCake.setText(pCoffeeCake);
            
        }
    }//GEN-LAST:event_jChkLagosMouseClicked

    private void jChkKillburnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkKillburnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkKillburnActionPerformed

    private void jChkKillburnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkKillburnMouseClicked
        // TODO add your handling code here
        
        double cKillburn=Double.parseDouble(jlblCostCake.getText());
        double Killburn=Double.parseDouble(jtxtKillburn.getText());
        double iKillburn=70.00;
        
        if(jChkKillburn.isSelected())
        {
            i[9]=(Killburn*iKillburn)+cKillburn;
            String pCoffeeCake=String.format("%.2f", i[9]);
            jlblCostCake.setText(pCoffeeCake);
            
        }
    }//GEN-LAST:event_jChkKillburnMouseClicked

    private void jChkQueensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkQueensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkQueensActionPerformed

    private void jChkQueensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkQueensMouseClicked
        // TODO add your handling code here:
        
        double cQueens=Double.parseDouble(jlblCostCake.getText());
        double Queens=Double.parseDouble(jtxtQueens.getText());
        double iQueens=77.00;
        
        if(jChkKillburn.isSelected())
        {
            i[10]=(Queens*iQueens)+cQueens;
            String pCoffeeCake=String.format("%.2f", i[10]);
            jlblCostCake.setText(pCoffeeCake);
            
        }
    }//GEN-LAST:event_jChkQueensMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
      
        //========================
        tk[0]=Double.parseDouble(jlblCostDrinks.getText());
        tk[1]=Double.parseDouble(jlblCostCake.getText());
        tk[2]=Double.parseDouble(jlblService.getText());
        
        
        
        double cTotal=(tk[0]+tk[1]+tk[2]);
        
        String iTaxTotal=String.format("%.2f",cTotal/100);
        jlblTax.setText(iTaxTotal);
        
        double SubTotal=(cTotal);
        String iSubTotal=String.format("%.2f",SubTotal);
        jlblSubTotal.setText(iSubTotal);
        
        double AllTotal=(cTotal);
        String iTotal=String.format("%.2f", AllTotal +(AllTotal/100) );
        jlblTotal.setText(iTotal);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLattleMouseClicked
        // TODO add your handling code here:
        jtxtLattle.setText(null);
    }//GEN-LAST:event_jtxtLattleMouseClicked

    private void jtxtIcedLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIcedLattleMouseClicked
        // TODO add your handling code here:
        jtxtIcedLattle.setText(null);
    }//GEN-LAST:event_jtxtIcedLattleMouseClicked

    private void jtxtCuppuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCuppuccinoMouseClicked
        // TODO add your handling code here:
        jtxtCuppuccino.setText(null);
    }//GEN-LAST:event_jtxtCuppuccinoMouseClicked

    private void jtxtIceCuppuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIceCuppuccinoMouseClicked
        // TODO add your handling code here:
        jtxtIceCuppuccino.setText(null);
    }//GEN-LAST:event_jtxtIceCuppuccinoMouseClicked

    private void jtxtEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEspressoMouseClicked
        // TODO add your handling code here:
        jtxtEspresso.setText(null);
    }//GEN-LAST:event_jtxtEspressoMouseClicked

    private void jtxtCoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCoffeeMouseClicked
        // TODO add your handling code here:
        jtxtCoffee.setText(null);
    }//GEN-LAST:event_jtxtCoffeeMouseClicked

    private void jtxtRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtRedMouseClicked
        // TODO add your handling code here:
        jtxtRed.setText(null);
    }//GEN-LAST:event_jtxtRedMouseClicked

    private void jtxtBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBlackMouseClicked
        // TODO add your handling code here:
        jtxtBlack.setText(null);
    }//GEN-LAST:event_jtxtBlackMouseClicked

    private void jtxtLagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLagosMouseClicked
        // TODO add your handling code here:
        jtxtLagos.setText(null);
    }//GEN-LAST:event_jtxtLagosMouseClicked

    private void jtxtKillburnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtKillburnMouseClicked
        // TODO add your handling code here:
        jtxtKillburn.setText(null);
        
    }//GEN-LAST:event_jtxtKillburnMouseClicked

    private void jtxtQueensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtQueensMouseClicked
        // TODO add your handling code here:
        
        jtxtQueens.setText(null);
    }//GEN-LAST:event_jtxtQueensMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Coffee_Shop_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Coffee_Shop_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Coffee_Shop_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Coffee_Shop_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Coffee_Shop_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jChkBlack;
    private javax.swing.JCheckBox jChkCoffeeCake;
    private javax.swing.JCheckBox jChkCuppuccino;
    private javax.swing.JCheckBox jChkEspresso;
    private javax.swing.JCheckBox jChkIceCuppuccno;
    private javax.swing.JCheckBox jChkIcedLattle;
    private javax.swing.JCheckBox jChkKillburn;
    private javax.swing.JCheckBox jChkLagos;
    private javax.swing.JCheckBox jChkLattle;
    private javax.swing.JCheckBox jChkQueens;
    private javax.swing.JCheckBox jChkRed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jlblCostCake;
    private javax.swing.JTextField jlblCostDrinks;
    private javax.swing.JTextField jlblService;
    private javax.swing.JTextField jlblSubTotal;
    private javax.swing.JTextField jlblTax;
    private javax.swing.JTextField jlblTotal;
    private javax.swing.JTextField jtxtBlack;
    private javax.swing.JTextField jtxtCoffee;
    private javax.swing.JLabel jtxtCostCake;
    private javax.swing.JLabel jtxtCostDrinks;
    private javax.swing.JTextField jtxtCuppuccino;
    private javax.swing.JTextField jtxtEspresso;
    private javax.swing.JTextField jtxtIceCuppuccino;
    private javax.swing.JTextField jtxtIcedLattle;
    private javax.swing.JTextField jtxtKillburn;
    private javax.swing.JTextField jtxtLagos;
    private javax.swing.JTextField jtxtLattle;
    private javax.swing.JTextField jtxtQueens;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtRed;
    private javax.swing.JLabel jtxtService;
    private javax.swing.JLabel jtxtSubTotal;
    private javax.swing.JLabel jtxtTax;
    private javax.swing.JLabel jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
